# Pull the Node image from Docker Hub
FROM node:14-slim

RUN apt-get update
RUN apt-get install -y libssl-dev

# Setting Working Directory
WORKDIR /usr/app

# Copying only package.json
COPY package*.json ./

# Install Dependencies
RUN npm install

RUN npm i -g nodemon

# Copy rest of the code to container
COPY . .

WORKDIR /usr/app/src

EXPOSE 3030
EXPOSE 5555

# Run the API on Nodemon
CMD ["npm", "run", "start"]